module.exports = {
  collectCoverage: true,
  collectCoverageFrom: ['./client/src/**/*.js',
                        './client/src/**/*.jsx',
                        "**/*.{js,jsx}",
                        "!**/server/**",
                        "!**/node_modules/**",
                        "!**/*.config.js",
                        "!**/bundle.js",
                        "!**/server/*",
                        '!**/server/helpers/*',
                        "!**/coverage/**"],
  coverageDirectory: 'coverage',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
};